### ISSUE TITLE
NPM Start Error Node 4.4.4 and NPM 2.15.1 - Windows 10

### ISSUE THREAD

**Issue by danielduckworth** [start-angular/SB-Admin-BS4-Angular-2#13]
Tried to run npm start and got the following output:

> angular2-seed@0.0.0 start E:\Google Drive\Software Development\Shift\test\project
> gulp serve --env dev

[19:01:38] Requiring external module ts-node/register
----------------------------------
⨯ Unable to compile TypeScript

gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)
tools\config.ts (1,28): Cannot find module 'fs'. (2307)
tools\config.ts (2,20): Cannot find module 'yargs'. (2307)
tools\config.ts (3,31): Cannot find module 'path'. (2307)
tools\config.ts (13,52): Cannot find name '__dirname'. (2304)
tools\config.ts (119,50): Cannot find name 'require'. (2304)
tools\manual_typings\merge-stream.d.ts (2,36): Cannot find namespace 'NodeJS'. (2503)
tools\manual_typings\merge-stream.d.ts (3,33): Cannot find namespace 'NodeJS'. (2503)
tools\manual_typings\merge-stream.d.ts (4,17): Cannot find namespace 'NodeJS'. (2503)
tools\utils.ts (9,17): Cannot find name 'require'. (2304)
tools\utils\code_change_tools.ts (1,26): Cannot find module 'express'. (2307)
tools\utils\code_change_tools.ts (6,20): Cannot find module 'path'. (2307)
tools\utils\code_change_tools.ts (45,18): Cannot find name 'process'. (2304)
tools\utils\server.ts (3,23): Cannot find module 'gulp-util'. (2307)
tools\utils\server.ts (4,26): Cannot find module 'express'. (2307)
tools\utils\server.ts (6,30): Cannot find module 'serve-static'. (2307)
tools\utils\server.ts (8,23): Cannot find module 'path'. (2307)
tools\utils\server.ts (32,25): Cannot find name 'process'. (2304)
tools\utils\tasks_tools.ts (1,23): Cannot find module 'gulp'. (2307)
tools\utils\tasks_tools.ts (2,23): Cannot find module 'gulp-util'. (2307)
tools\utils\tasks_tools.ts (3,24): Cannot find module 'chalk'. (2307)
tools\utils\tasks_tools.ts (4,34): Cannot find module 'gulp-load-plugins'. (2307)
tools\utils\tasks_tools.ts (5,31): Cannot find module 'run-sequence'. (2307)
tools\utils\tasks_tools.ts (6,50): Cannot find module 'fs'. (2307)
tools\utils\tasks_tools.ts (7,20): Cannot find module 'path'. (2307)
tools\utils\tasks_tools.ts (19,10): Cannot find name 'require'. (2304)
tools\utils\template_injectables.ts (4,20): Cannot find module 'path'. (2307)
----------------------------------

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve --env dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 start script 'gulp serve --env dev'.
npm ERR! This is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve --env dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Google Drive\Software Development\Shift\test\project\npm-debug.log

-- Here is the contents of npm-debug.log --

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart angular2-seed@0.0.0
6 info start angular2-seed@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info angular2-seed@0.0.0 Failed to exec start script
9 verbose stack Error: angular2-seed@0.0.0 start: `gulp serve --env dev`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid angular2-seed@0.0.0
11 verbose cwd E:\Google Drive\Software Development\Shift\test\project
12 error Windows_NT 10.0.10586
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.4.4
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error angular2-seed@0.0.0 start: `gulp serve --env dev`
17 error Exit status 1
18 error Failed at the angular2-seed@0.0.0 start script 'gulp serve --env dev'.
18 error This is most likely a problem with the angular2-seed package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp serve --env dev
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs angular2-seed
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls angular2-seed
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by donaldhook** [comment]
I get the same thing ...

**Comment by Neo478** [comment]
Same here, but i had some errors during the install. After looking at the errors i saw that "node-gyp rebuild failed, so i ran it:

gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@5.0.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\...\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'Z:\\...\\SB-Admin-BS4-Angular-2-master\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\...\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\...\\.node-gyp\\5.0.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\...\\.node-gyp\\5.0.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\...\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=Z:\\...\\SB-Admin-BS4-Angular-2-master',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'Z:\\...\\SB-Admin-BS4-Angular-2-master\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: Z:\...\SB-Admin-BS4-Angular-2-master) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\...\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\...\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd Z:\...\SB-Admin-BS4-Angular-2-master
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

npm version: 3.3.6
node version: 5.0.0

Please not the line "binding.gyp not found (cwd: Z:\...\SB-Admin-BS4-Angular-2-master) while trying to load binding.gyp"
Maybe binding.gyp isn't push on github?

**Comment by nitinkumarmishra** [comment]
install `node-gyp` globally for that `npm install -g node-gyp`
Python (v2.7.10 recommended, v3.x.x is not supported) use link https://www.python.org/downloads/release/python-2710/
npm rebuild node-sass (if required)

may be it will resolve issue if not try following Steps:
1: MSBuild Tool 2013 use `https://www.microsoft.com/en-in/download/confirmation.aspx?id=40760`
2: `ts-node` installed globally  `npm install -g ts-node` 
3: Run the Command Prompt  with administrator privileges.
4: npm install —msvs_version=2013
5: npm start
