### ISSUE TITLE
Unable to compile TypeScript

### ISSUE THREAD

**Issue by chandra10207** [start-angular/SB-Admin-BS4-Angular-2#14]
Hi all,
I am new to AngularJS. 
During theme setup an error: occured while running npm start command. i had also attached the screenshoot  of this error.
Please see and send me the feedback.

![sb-admin-error](https://cloud.githubusercontent.com/assets/9652251/15664064/a9979356-2720-11e6-84c7-3e96e340bb5e.png)

**Comment by qgillet** [comment]
I have the exact same issue

**Comment by nitinkumarmishra** [comment]
make sure you have 
1) node, npm `https://nodejs.org/en/download/`
2) gulp `npm install -g gulp`
3) ts-node `npm install -g ts-node`
I tested it on ubuntu 14.04 with node 4.* and npm 2.*. it worked fine. if it doesn't work just send npm-debug.log
