### ISSUE TITLE
Hello from ng2-bootstrap

### ISSUE THREAD

**Issue by valorkin** [start-angular/SB-Admin-BS4-Angular-2#15]
Hi guys, I would love to help you with ng2 version
I am author of https://github.com/valor-software/ng2-bootstrap
May be it can be useful for you

**Comment by valorkin** [comment]
PS I have seen guys are trying to achieve this
http://angularshowcase.github.io/ng2-bootstrap-sbadmin/

**Comment by sanketsahusoft** [comment]
Hey @valorkin, great to connect with you here. At the moment, we have got the first version but we are too busy with other things, if you want to improve, you can help and send the pull request. I will get it merged. 👍

**Comment by valorkin** [comment]
ok, I will do in nearest time
