### ISSUE TITLE
Blank page on iPad Chrome & Safari

### ISSUE THREAD

**Issue by jboothe** [start-angular/SB-Admin-BS4-Angular-2#17]
The demo site displays blank page on iPad Chrome 49.0.2623.109 and Safari
http://rawgit.com/start-angular/SB-Admin-BS4-Angular-2/master/dist/prod/index.html

**Comment by shwetapal** [comment]
There is some issue in the demo, we will be fixing it soon. You can try the repo meanwhile it will work fine.

**Comment by nitinkumarmishra** [comment]
For demo we use `http://rawgit.com/start-angular/SB-Admin-BS4-Angular-2/master/dist/prod/index.html` but angular rc1 routing has changed so it try to find root at `http://rawgit.com/` but path is `start-angular/SB-Admin-BS4-Angular-2/master/dist/prod/index.html` so it throw error `no mathcing route` found. We will fix it soon.
It will work fine on your local system(both development and production)
