### ISSUE TITLE
Firefox and FontAwesome aren't working well

### ISSUE THREAD

**Issue by mikesocha3** [start-angular/SB-Admin-BS4-Angular-2#18]
The Font Awesome icons don't work right in Firefox

![firefox fa issue](https://cloud.githubusercontent.com/assets/6980079/16286509/81a4fda0-38a2-11e6-8ad6-a98594714041.png)

**Comment by shwetapal** [comment]
In the constructor function of project.config.ts file write this { src: 'font-awesome/css/font-awesome.css', inject: true}. The firefox issue will be solved.

**Comment by yeungocanh** [comment]
I dont know exactly where is `project.config.ts`. I met this issue again with newest code.
Thanks for any help!
