### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by calvimor** [start-angular/SB-Admin-BS4-Angular-2#2]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_mo                                                                                                                  dules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm-debug.log's content

[npm-debug.log.txt](https://github.com/start-angular/SB-Admin-BS4-Angular-2/files/134800/npm-debug.log.txt)

**Comment by nabinkumarn** [comment]
I am also having the same issue. Any solutions??

**Comment by nitinkumarmishra** [comment]
I tested it on  my pre formated windows 10
make sure you have `node-gyp` installed globally for that `npm install -g node-gyp`
Python (v2.7.10 recommended, v3.x.x is not supported) use link https://www.python.org/downloads/release/python-2710/
npm rebuild node-sass (if required)
run `npm start `

**Comment by nabinkumarn** [comment]
still getting the error.

**Comment by nabinkumarn** [comment]
```
D:\OfficeWorks\angularjs\SB-Admin-BS4-Angular-2-master  (angular2-seed@0.0.0)    
λ npm install                                                                    
                                                                                 
> contextify@0.1.15 install D:\OfficeWorks\angularjs\SB-Admin-BS4-Angular-2-maste
> node-gyp rebuild                                                               
                                                                                 
                                                                                 
D:\OfficeWorks\angularjs\SB-Admin-BS4-Angular-2-master\node_modules\contextify {g
{lamb} if not defined npm_config_node_gyp (node "C:\Users\nabin\AppData\Roaming\n
ild )  else (node  rebuild )                                                     
Building the projects in this solution one at a time. To enable parallel build, p
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". T
2005 or 3) add the location of the component to the system path if it is installe
textify\build\binding.sln]                                                       
gyp ERR! build error                                                             
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe`
gyp ERR! stack     at ChildProcess.onExit (C:\Users\nabin\AppData\Roaming\npm\nod
gyp ERR! stack     at emitTwo (events.js:87:13)                                  
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)                        
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process
gyp ERR! System Windows_NT 10.0.10586                                            
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nabin\\AppData
gyp ERR! cwd D:\OfficeWorks\angularjs\SB-Admin-BS4-Angular-2-master\node_modules\
gyp ERR! node -v v4.3.1                                                          
gyp ERR! node-gyp -v v3.0.3                                                      
gyp ERR! not ok                                                                  
angular2-seed@0.0.0 D:\OfficeWorks\angularjs\SB-Admin-BS4-Angular-2-master       
└── node-gyp-install@2.2.0  extraneous                                           
                                                                                 
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:        
npm WARN notsup Not compatible with your operating system or architecture: fseven
npm WARN In node-gyp-install@2.2.0 replacing bundled version of npmlog with npmlo
npm WARN In node-gyp-install@2.2.0 replacing bundled version of semver with semve
npm WARN In c3@0.4.11-rc4 replacing bundled version of d3 with d3@3.5.0          
npm ERR! Windows_NT 10.0.10586                                                   
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nabin\\AppData\\R
npm ERR! node v4.3.1                                                             
npm ERR! npm  v3.5.0                                                             
npm ERR! code ELIFECYCLE                                                         
                                                                                 
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`                           
npm ERR! Exit status 1                                                           
npm ERR!                                                                         
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.      
npm ERR! Make sure you have the latest version of node.js and npm installed.     
npm ERR! If you do, this is most likely a problem with the contextify package,   
npm ERR! not with npm itself.                                                    
npm ERR! Tell the author that this fails on your system:                         
npm ERR!     node-gyp rebuild                                                    
npm ERR! You can get their info via:                                             
npm ERR!     npm owner ls contextify                                             
npm ERR! There is likely additional logging output above.                        
                                                                                 
npm ERR! Please include the following file with any support request:             
npm ERR!     D:\OfficeWorks\angularjs\SB-Admin-BS4-Angular-2-master\npm-debug.log
```
[npm-debug.txt](https://github.com/start-angular/SB-Admin-BS4-Angular-2/files/139468/npm-debug.txt)

**Comment by nitinkumarmishra** [comment]
try this  `node-gyp rebuild`

**Comment by nabinkumarn** [comment]
I get this error.

λ node-gyp rebuild
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.0
gyp info using node@4.3.1 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\nabin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\OfficeWorks\\angularjs\\SB-Admin-BS4-Angular-2\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nabin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\nabin\\.node-gyp\\4.3.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\nabin\\.node-gyp\\4.3.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\nabin\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\OfficeWorks\\angularjs\\SB-Admin-BS4-Angular-2',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\OfficeWorks\\angularjs\\SB-Admin-BS4-Angular-2\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: D:\OfficeWorks\angularjs\SB-Admin-BS4-Angular-2) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\nabin\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nabin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\OfficeWorks\angularjs\SB-Admin-BS4-Angular-2
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
```

**Comment by nbjones** [comment]
I'm also having issues, my debug log is listed below. Any advice?

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-seed@0.0.0~prestart: angular2-seed@0.0.0
6 silly lifecycle angular2-seed@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular2-seed@0.0.0~start: angular2-seed@0.0.0
8 verbose lifecycle angular2-seed@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-seed@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/nora.jones/Downloads/SB-Admin-BS4-Angular-2-master/node_modules/.bin:node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle angular2-seed@0.0.0~start: CWD: /Users/nora.jones/Downloads/SB-Admin-BS4-Angular-2-master
11 silly lifecycle angular2-seed@0.0.0~start: Args: [ '-c', 'gulp serve --env dev' ]
12 silly lifecycle angular2-seed@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular2-seed@0.0.0~start: Failed to exec start script
14 verbose stack Error: angular2-seed@0.0.0 start: `gulp serve --env dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular2-seed@0.0.0
16 verbose cwd /Users/nora.jones/Downloads/SB-Admin-BS4-Angular-2-master
17 error Darwin 15.3.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.5.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error angular2-seed@0.0.0 start: `gulp serve --env dev`
22 error Exit status 1
23 error Failed at the angular2-seed@0.0.0 start script 'gulp serve --env dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-seed package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp serve --env dev
23 error You can get their info via:
23 error     npm owner ls angular2-seed
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by nabinkumarn** [comment]
Has anyone got the solution?

**Comment by nitinkumarmishra** [comment]
@nabinkumarn , @nbjones this problem occurs on Windows system because of  node-gyp is no longer being actively developed  and so it has some old dependencies that a modern development env might not have and right now there is no solution, i think test it on other environment.

**Comment by nabinkumarn** [comment]
Thanks @jj-jiles for steps. I have done everything already except this `npm install --msvs_version=2015`(mine is 2013).Including that tag I got no error in npm install but my bad I got error in `npm start`..
```
`npm start

> angular2-seed@0.0.0 start D:\OfficeWorks\angularjs\SB-Admin-BS4-Angular-2
> gulp serve --env dev

[00:49:43] Requiring external module ts-node/register
[00:50:07] Loading task clean all
[00:50:09] Loading task clean dist
[00:50:09] Loading task clean test
[00:50:09] Loading task clean tmp
[00:50:09] Loading task check.versions
[00:50:10] Loading task build.docs
[00:50:11] Loading task serve.docs
[00:50:13] Using gulpfile D:\OfficeWorks\angularjs\SB-Admin-BS4-Angular-2\gulpfile.ts
[00:50:13] Starting 'serve'...
[00:50:13] Loading task server.start
[00:50:15] Loading task watch.serve
[00:50:17] Starting 'build.dev'...
[00:50:17] Loading task tslint
[00:50:18] Loading task build.sass.dev
[00:50:19] Loading task build.assets.dev
[00:50:20] Loading task build.js.dev
[00:50:21] Loading task build.index.dev
[00:50:23] Starting 'clean.dist'...
[00:50:23] Deleted -
[00:50:23] Finished 'clean.dist' after 14 ms
[00:50:23] Starting 'tslint'...

D:\OfficeWorks\angularjs\SB-Admin-BS4-Angular-2\app\hot_loader_main.ts
      line 11  col 6  file should end with a newline

    × 1 error

[00:50:28] 'tslint' errored after 4.52 s
[00:50:28] Error in plugin 'gulp-tslint'
Message:
    Failed to lint: hot_loader_main.ts[11, 6]: file should end with a newline.
[00:50:28] 'serve' errored after 15 s
[00:50:28] Error in plugin 'run-sequence'
Message:
    An error occured in task 'tslint'.
[00:50:28] 'build.dev' errored after 11 s
[00:50:28] Error in plugin 'run-sequence'
Message:
    An error occured in task 'serve'.
[00:50:28] 'build.dev' errored after 11 s
[00:50:28] Error in plugin 'run-sequence'
Message:
    An error occured in task 'tslint'.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve --env dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 start script 'gulp serve --env dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve --env dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above
```.`
I guess it is the error in the hot_loader_main.ts file but I am new to ts can you help?

**Comment by jj-jiles** [comment]
@nabinkumarn I'm new also. It's been an interesting learning experience.

tslint has a few settings in the tslint.json file. One of those settings is requiring that all .ts files end with a new line, as well as 'no-trailing-whitespace'. I'm pointing this out because these are the two that really got me during the first few starts. So, open your '\app\hot_loader_main.ts' file and an empty line at the end of the file and try 'npm start' again.

**Comment by nabinkumarn** [comment]
@jj-jiles Thanks, finally it worked. I did as you said plus I remove node-sass and install again as rebuild was showing error..Anyway it worked, thanks

**Comment by jj-jiles** [comment]
@nabinkumarn glad it worked. You may need node-sass though. I'm fairly certain it's the pre-processor for the .scss (SASS) files for your CSS. You don't have to use SASS, but if you decide to, you'll need to reinstall it. 

As a suggestion: SASS or LESS is definitely worth looking into using.
