### ISSUE TITLE
Which license is the project using?

### ISSUE THREAD

**Issue by guw** [start-angular/SB-Admin-BS4-Angular-2#20]
The readme shows a directory tree with a LICENSE file but there is non in the Git repository. Please provide one. Would be great to know what OS license this project is using.

**Comment by guw** [comment]
@nitinkumarmishra Is this resolved or is the project not using any open source license?

**Comment by perusal** [comment]
@guw That's okay. We haven't kept any License as such, must have been a mistake. As we say on our website, `our themes are open source for any use, even commercial.`

**Comment by guw** [comment]
@nitinkumarmishra Are you referring to this license: http://www.strapui.com/licenses/?

I think It's not easy to discover. IMO, the connection to the website is not obvious. Thus, please put either a simple LICENSE text file into the Git repo and/or add a paragraph with one sentence to the README pointing to the URL mentioned above. 

Otherwise you are loosing a lot of potential. Quite a lot organizations require clear licensing for any OSS usage. Without it, developers can't even look at your stuff - not to mention contributing back.

**Comment by perusal** [comment]
@guw `StrapUI` is different. That is another website for premium themes. We keep our own custom License there. 
This one is of `StartAngular`; there is no as such licensing. We'll keep an open source one maybe just to avoid confusion like this.
For now, all you need to know that this is `free and open source for any use, even commercial.`.

**Comment by guw** [comment]
@nitinkumarmishra I'm sorry. This is request is not just for me but for a lot other developers out there. The clause "free and open source for any use, even commercial" is nice but not helpful at all unless you write it into a LICENSE file somewhere in the Git repo (or in the README). This versions the license with the source code and allows developers to use that particular version. You can change the license later on if you want. The older versions of the Git repo are guaranteed to be available under a previous used license. Otherwise the risk to too large for legal and they won't allow developers to use your code.

Also, I really recommend going with a common license. Those are in general approved at larger organizations and don't require a legal review. From my experience, the few words  "free and open source for any use, even commercial" are likely too ambiguous and will not pass a legal review.

http://choosealicense.com/
https://help.github.com/articles/open-source-licensing/

**Comment by perusal** [comment]
@guw That makes sense. Here, https://github.com/start-angular/SB-Admin-BS4-Angular-2/blob/master/LICENSE
We added an MIT License. 
Now, you can go ahead with your development.

**Comment by guw** [comment]
Thanks a lot!
