### ISSUE TITLE
how to update to angular rc4

### ISSUE THREAD

**Issue by ksngits** [start-angular/SB-Admin-BS4-Angular-2#21]
how to upgrade to angular rc4

**Comment by nitinkumarmishra** [comment]
It's little bit difficult to update to rc-4, we will update it soon. If you want rc-4 we have one premium theme http://www.strapui.com/themes/ani-angular-2-bootstrap-4-theme which you can try

**Comment by supermarcos** [comment]
It is not only about changing dependencies... You will face the most of the problems with the router, but you can find nice samples in ng2-admin repo, for instance, so you can use it as reference.

**Comment by nstone101** [comment]
Hi now If I wanted to Deploy this to something Heroku or just basic Linux based server via FTP how can I go about doing that, in other projects using Webpack and other things I've had similar issues. I should only needs certain folders and files, and obviously don't need live reloads and things of that nature. I just want to test a few of my plugins but having quite a challenge doing so....very cool stuff by the way, great job on this. very appealing. I have a lot of people that have different admin boards similar but I'm working on social media integration, I want a private testable admin board to play with in multiple deployed versions... I assume enabling a production mode in NODE ENV, I mean what else do I have to all, all my attempts have left me with a blank loaded page.

**Comment by nitinkumarmishra** [comment]
Steps are described in following link
https://github.com/mgechev/angular2-seed/wiki/Deploying-prod-build-to-Apache-2

**Comment by 7200rpm** [comment]
I would also be very interested in upgrading to rc4. I was able to move to the new router without too much trouble, but when I updated to rc4 in package.json and did a npm install, it freaked out about something with typings and gulp. Any idea what steps are necessary?

**Comment by nitinkumarmishra** [comment]
you should try https://github.com/mgechev/angular2-seed
