### ISSUE TITLE
top menu arent showing on mobile devices

### ISSUE THREAD

**Issue by stocksph** [start-angular/SB-Admin-BS4-Angular-2#22]
Hi,

         I was wondering why the top menu are not showing on mobile devices?

        Looking forward to hear from you soon.

Sincerely
Johny

**Comment by nitinkumarmishra** [comment]
it is working in iphone 6
![screen shot 2016-07-23 at 9 29 53 am](https://cloud.githubusercontent.com/assets/14124584/17075655/20403a38-50b8-11e6-86f6-584ce2e9f9ce.png)
Can you tell me what is the problem?(exactly)

**Comment by stocksph** [comment]
it doesnt show up the menu of the "top menu" when you're using mobile or smaller screen.

top menu are the user(login/logout), bell reminder, message etc.

but the sidebar menu is looking great on mobile devices.
just the top menu that isnt working on mobile devices.

**Comment by nitinkumarmishra** [comment]
We will fix it in next release.
