### ISSUE TITLE
Upgraded Angular 2 RC5 Routes Deprecated

### ISSUE THREAD

**Issue by drychlik76** [start-angular/SB-Admin-BS4-Angular-2#26]
It appears that routes have been deprecated in RC5 in favor of what appears NgModule and RouteModule.  Any plans to update this repo to use RC5?  It appears that the Angular 2 team is getting closer to a final release based from RC5.

**Comment by PiXeL16** [comment]
+1. It would be really nice to have it running in RC5.

**Comment by ThisIsRuddy** [comment]
+1 Please.

**Comment by nitinkumarmishra** [comment]
we will update it in the next couple of days.
