### ISSUE TITLE
Upgrad to Angular2-RC6 support

### ISSUE THREAD

**Issue by Nishchit14** [start-angular/SB-Admin-BS4-Angular-2#28]
Recently Angular2 team released Angular2-RC6. So is there any plan to give support for RC6 ?

What's new in RC6 ? - http://angularjs.blogspot.in/2016/09/angular-2-rc6_1.html
Change Log - https://github.com/angular/angular/blob/master/CHANGELOG.md

It has not any major changes, So it will not a big code changing. And will help for future release updation also.

**Comment by nitinkumarmishra** [comment]
updated to rc6
