### ISSUE TITLE
Error in build.prod

### ISSUE THREAD

**Issue by bongiova61** [start-angular/SB-Admin-BS4-Angular-2#29]
After downloading commit #2dd5bbe , installation and launck s OK, but build.prod failed with errors.
Attach log of "npm run build.prod"
[build.prod.zip](https://github.com/start-angular/SB-Admin-BS4-Angular-2/files/464319/build.prod.zip)

**Comment by nitinkumarmishra** [comment]
add `gulp.src('node_modules/moment/moment.js').pipe(gulp.dest('./node_modules'));`
in gulpfile.ts before `loadTasks(SEED_TASKS_DIR);`

**Comment by bongiova61** [comment]
Solved!
