### ISSUE TITLE
HighCharts

### ISSUE THREAD

**Issue by bcrigler** [start-angular/SB-Admin-BS4-Angular-2#3]
Getting these errors on HighCharts you added I think yesterday?  

app/pages/charts/components/charts.ts(11,19): error TS2339: Property 'highcharts' does not exist on type 'ElementFinder'.
app/pages/charts/components/charts.ts(66,20): error TS2339: Property 'highcharts' does not exist on type 'ElementFinder'.
app/pages/charts/components/charts.ts(90,24): error TS2339: Property 'highcharts' does not exist on type 'ElementFinder'.
app/pages/charts/components/charts.ts(143,26): error TS2339: Property 'highcharts' does not exist on type 'ElementFinder'.

**Comment by nitinkumarmishra** [comment]
you can use this syntax `var container:any = $('#container');` and then call the highchart function.
