### ISSUE TITLE
webpack support

### ISSUE THREAD

**Issue by Nishchit14** [start-angular/SB-Admin-BS4-Angular-2#30]
Webpack is very famous for package bundle and dev-server.
Is webpack in roadmap ?
 Now NG2 team officially declare webpack in their best practices. https://angular.io/docs/ts/latest/guide/webpack.html

**Comment by nitinkumarmishra** [comment]
we will use webpack in next release

**Comment by hernanBeiza** [comment]
Hi! Any option to compile using Angular CLI?

**Comment by kevinsoltis41** [comment]
+1 for Angular CLI option?

**Comment by robinmaple** [comment]
+1 for Angular CLI as well:) Any target date for the next release for webpack, please? Thanks!

**Comment by nitinkumarmishra** [comment]
done
