### ISSUE TITLE
Modal using Rc6

### ISSUE THREAD

**Issue by Dapaulor** [start-angular/SB-Admin-BS4-Angular-2#32]
I'm trying to add a [ng2-bootstrap](https://github.com/valor-software/ng2-bootstrap) modal. I'm able to add other components from ng2-bootstrap such as alerts, pagination and tooltips but I cannot add a modal component.

Once I followed the installation steps, I add Ng2BootstrapModule in `dashboard.module.ts` and finally insert the modal in the html file:
```html
<!-- Small modal -->
<button type="button" class="btn btn-primary" (click)="smModal.show()">Small modal</button>
 
<div bsModal #smModal="bs-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" aria-label="Close" (click)="smModal.hide()">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Small modal</h4>
      </div>
      <div class="modal-body">
        <!-- Body content -->
      </div>
    </div>
  </div>
</div>
```
When I try `$ npm start`, the application does not pass from loading view. If I remove the hash symbol from: `#smModal="bs-modal"`the application is lauched but unable to popup the modal. 
Any help?

Note:
The hack in the root component is added
```typescript
import {Component, ViewContainerRef} from '@angular/core';

@Component({selector:'app-root'})
class AppRoot {
  public constructor(viewContainerRef:ViewContainerRef) {
    // You need this small hack in order to catch application root view container ref
    this.viewContainerRef = viewContainerRef;
  }
}
```
UPDATE: It happens the same for datepicker components and possibly other components from ng2-bootstrap which are not included in the original SB-Admin-BS4-Angular-2 theme.

**Comment by mega5329** [comment]
Inside the file, _app-base.scss, comment out z-index under .main-container, It will work for modal

**Comment by Dapaulor** [comment]
Thank you very much @mega5329 , it worked! However other components from ng2-bootstrap cannot work such as datepicker. I guess it must be about style problems though I tried to figure it out I did not find it.
