### ISSUE TITLE
Failed to setup project

### ISSUE THREAD

**Issue by aldrindizonh** [start-angular/SB-Admin-BS4-Angular-2#36]
Failed to setup project.

I encounter problem when i start running npm start 
<img width="1173" alt="screen shot 2016-09-15 at 11 54 44 am" src="https://cloud.githubusercontent.com/assets/17155863/18537897/3e27c180-7b3b-11e6-8583-af606e89a470.png">

**Comment by nitinkumarmishra** [comment]
just remove whitespace in line no 50 from `bsComponent.component.ts` file
