### ISSUE TITLE
extract zone.js

### ISSUE THREAD

**Issue by paklei** [start-angular/SB-Admin-BS4-Angular-2#41]
When I run the npm install; the shell shows something like:

> extract:zone.js: sill doParallel extract 1193

and never ends...I've been waiting for hours.

**Comment by nitinkumarmishra** [comment]
please provide us your system info like node version & os & gulp etc

**Comment by paklei** [comment]
Same issue with another OS

 uname -a

> Linux Regina 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

 node -v

> v6.2.1

npm -v

> 3.9.3

gulp -v

> [12:39:59] CLI version 3.9.1

npm install
fetchMetadata → network   ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
^Z
[1]+  Stoped                npm install

**Comment by paklei** [comment]
I Solved this issue after update the node version to 6.6.0
>     node -v && npm -v
>     v6.6.0
>     3.10.8

But now I see the next output when I run the npm start command:

> [holo@archpc meanAdmin]$ npm start
>  SB-Admin-BS4-Angular-2@0.0.0 start /home/holo/meanAdmin
> gulp serve.dev --color
> 
> [21:25:38] Requiring external module ts-node/register
> [21:25:39] Loading tasks folder /home/holo/meanAdmin/tools/tasks/seed
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/build.assets.dev
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/build.assets.prod
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/build.bundles.app.exp
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/build.bundles.app
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/build.bundles
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/build.docs
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/build.html_css
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/build.index.dev
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/build.index.prod
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/build.js.dev
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/build.js.e2e
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/build.js.prod.exp
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/build.js.prod
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/build.js.test
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/build.js.tools
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/check.versions
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/clean.all
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/clean.coverage
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/clean.dev
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/clean.prod
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/clean.tools
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/compile.ahead.prod
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/copy.prod
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/css-lint
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/e2e
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/generate.manifest
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/karma.run
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/karma.watch
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/minify.bundles
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/serve.coverage
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/serve.docs
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/server.prod
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/server.start
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/tslint
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/watch.dev
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/watch.e2e
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/watch.test
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/seed/webdriver
> [21:25:39] Loading tasks folder /home/holo/meanAdmin/tools/tasks/project
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/project/build.fonts
> [21:25:39] Registering task ~/meanAdmin/tools/tasks/project/sample.task
> [21:25:39] Using gulpfile ~/meanAdmin/gulpfile.ts
> [21:25:39] Starting 'serve.dev'...
> [21:25:39] Starting 'build.dev'...
> [21:25:39] Starting 'tslint'...
> [21:25:42] Finished 'tslint' after 3.24 s
> [21:25:42] Starting 'build.fonts'...
> [21:25:42] Finished 'build.fonts' after 23 ms
> [21:25:42] Starting 'build.assets.dev'...
> [21:25:42] Finished 'build.assets.dev' after 74 ms
> [21:25:42] Starting 'build.html_css'...
> [21:25:42] 'build.html_css' errored after 411 ms
> [21:25:42] Error: Cannot find module 'rxjs/bundles/Rx.umd.min.js'
>     at Function.Module._resolveFilename (module.js:455:15)
>     at Function.resolve (internal/module.js:27:19)
>     at /home/holo/meanAdmin/tools/config/seed.config.ts:526:59
>     at Array.forEach (native)
>     at normalizeDependencies (/home/holo/meanAdmin/tools/config/seed.config.ts:526:6)
>     at ProjectConfig.get [as DEPENDENCIES] (/home/holo/meanAdmin/tools/config/seed.config.ts:304:12)
>     at getExternalCss (/home/holo/meanAdmin/tools/tasks/seed/build.html_css.ts:124:10)
>     at getExternalCssStream (/home/holo/meanAdmin/tools/tasks/seed/build.html_css.ts:116:19)
>     at processAllExternalStylesheets (/home/holo/meanAdmin/tools/tasks/seed/build.html_css.ts:104:16)
>     at processExternalStylesheets (/home/holo/meanAdmin/tools/tasks/seed/build.html_css.ts:96:24)

**Comment by paklei** [comment]
Now it's running, I executed ncu command before the npm start command then I got that errors ... The template it's working just fine (I hope jeje) with the original package.json.
