### ISSUE TITLE
how to npm start with production environment

### ISSUE THREAD

**Issue by alexandreaniceto** [start-angular/SB-Admin-BS4-Angular-2#42]
Hi, i've tried to do 'npm start --config-env prod / production / Production.. many options with no luck.

How can I start with the production ENV ?

**Comment by nitinkumarmishra** [comment]
for production run `gulp build.prod`

**Comment by thebossza101** [comment]
how to build with production run on Xampp Server and how to config in https://domainname.com/project_path ?

**Comment by nitinkumarmishra** [comment]
We don't use xampp server and don't know more about it.
For production you may need .htaccess file, for that copy following code and paste it in .htaccess file

<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>
