### ISSUE TITLE
TypeScript support/tsconfig.json should include source

### ISSUE THREAD

**Issue by TimMensch** [start-angular/SB-Admin-BS4-Angular-2#44]
The tsconfig.json files exclude all of the actual TypeScript files. As a result, in VS Code I get tons of warnings and errors because the tsconfig settings aren't being applied. I recommend deleting the "files" section of `src/client/tsconfig.json`; then that tsconfig.json can apply to all the files under src/client, which I believe is appropriate, and which fixes the tooling issues.

However, after making this change and adding a "outDir" configuration line so the output doesn't end up scattered among the source directories, I tried running tsc, and it revealed two files will errors:
- test.component.spec.ts imports items that don't exist (seemingly?) from `@angular/forms/index` (I checked the actual exports, and they aren't in the export declarations, nor anywhere in the @angular tree according to grep)
- in src/client/app/main-prod.ts, it attempts to import './app.module.ngfactory', which doesn't exist.

I'm sure both of these are historical artifacts based on how Angular used to work or how the project used to be structured, but I wanted to file an issue since I assume you'll want to clean these up. 

The first looks like a problem with tests; in fact I get a pile of TypeScript errors when I "gulp test".

The second looks to me like it would prevent a production build from working; a little digging found where it breaks:

```
$ gulp build.js.prod.exp
...
[18:12:35] Starting 'build.js.prod.exp'...
dist\tmp\app\main-prod.ts(5,36): error TS2307: Cannot find module './app.module.ngfactory'.
[18:12:45] TypeScript: 1 semantic error
[18:12:45] TypeScript: emit succeeded (with errors)
```

The regular prod build works; not sure what the exp build is supposed to do, but it is in fact broken. 

Thought you'd want to know.

**Comment by nitinkumarmishra** [comment]
thanks @TimMensch, we will fix it soon.
