### ISSUE TITLE
How can I change the navbar and sidebar background color?

### ISSUE THREAD

**Issue by paklei** [start-angular/SB-Admin-BS4-Angular-2#45]
(This is not a issue, I just need help)
Hi everyone, I hope you someone could help me. I was traying to change the default color of the navbar and sidebar from black (or gray) to another but I can't.

This is my app.scss file

$gray-dark:                 #f71f1f;
$gray:                      #f71f1f;
$gray-light:                #f71f1f;
$gray-lighter:              #f71f1f;
$gray-lightest:             #f71f1f;

@import "../bootstrap/variables.scss";

$navbar-dark-color:                 #f71f1f;
$navbar-dark-hover-color:           #f71f1f;
$navbar-dark-active-color:          #f71f1f;
$navbar-dark-disabled-color:        #f71f1f;
$topnav-background-color: #ffffff;

@import "app-base.scss";

I Tried to make a _custom.scss file and import this, but it doesn't work... what's the correct way to do that?

Thanks!

**Comment by nitinkumarmishra** [comment]
go to /src/client/assets/sass/_app-base.scss and change whatever you want

**Comment by sbasi5576** [comment]
How do you change it in the latest version?    There is no /src/client/assets/sass/_app-base.scss

**Comment by vikneshpsy** [comment]
How to hide and show sidebar in desktop view? mobile view its working perfectly how to configure in desktop view?

**Comment by remmar02** [comment]
> How to hide or show sidebar in desktop view? mobile view its working perfectly how to configure in desktop view?

Hi, I`m following on this post `coz I`m having the same problem as you. Have you already resolved this?
