### ISSUE TITLE
Demo on RawGit 

### ISSUE THREAD

**Issue by juananinca** [start-angular/SB-Admin-BS4-Angular-2#46]
This is not any bug, I just need some help taking my demo to [RawGit](https://rawgit.com/) just as you did. 

Before I generate my prod dist I change the value of APP_BASE in the `tools/config/seed.config.ts` with `/githubusername/githubrepo/master/dist/prod/`.

I run `npm build.prod` first of all, and then push the changes on my github repository. I take the github URL of my index prod `dist/prod/index.html` and I paste it in RawGit main input field. I check the URL for development as well as the "in production" but both of them show me an 404: Not found.

What am I doing wrong?

**Comment by nitinkumarmishra** [comment]
in our case, I did `gulp build.prod --base /start-angular/SB-Admin-BS4-Angular-2/master/dist/prod/` 

you can do the same thing, just change path

**Comment by juananinca** [comment]
It was my fault. I was setting a wrong path... 
Thank you any way.
