### ISSUE TITLE
Divs disappear when width is large

### ISSUE THREAD

**Issue by assaflei** [start-angular/SB-Admin-BS4-Angular-2#51]
When using max window size in 24' screen divs which use col-_-_ disappear
I noticed there is a max width definition of 1200px which might not be enough in the files __bootstrap-grid.scss and _variables.scss files

Since the file is scss I'm not sure if I can simply edit it

Is there a standard way to set this max width property to a different value?

**Comment by nitinkumarmishra** [comment]
you can customize _grid.scss file and it mixin file
