### ISSUE TITLE
Side menu toggle icon not shown and can't be used

### ISSUE THREAD

**Issue by zh-wowtv** [start-angular/SB-Admin-BS4-Angular-2#54]
I used most of your code and integrate it to an angular2-meteor project. Please refer to:

https://github.com/zhouhao27/angular2-meteor-dashboard

But I got a problem, my menu toggle icon not shown and not working when I resize the browser to small size:

<img width="623" alt="2016-10-19 3 57 49" src="https://cloud.githubusercontent.com/assets/18462946/19510239/df459b3e-9614-11e6-843e-5e97aa4346ad.png">

Any suggestion? Thanks.

**Comment by nitinkumarmishra** [comment]
just write css media query for the toggle button (small screen)
