### ISSUE TITLE
error while running "npm start"

### ISSUE THREAD

**Issue by nasr18** [start-angular/SB-Admin-BS4-Angular-2#55]
I'm getting this error while running `npm start`

![npm start](https://cloud.githubusercontent.com/assets/7514936/19655367/3958bc64-9a39-11e6-8354-9ae9aa479f9e.png)

help me ASAP

**Comment by nitinkumarmishra** [comment]
install node (LTS 4.6.*)  from https://nodejs.org/en/
npm install 
npm start
