### ISSUE TITLE
How to add a node_module properly? 404 NOT FOUND on module

### ISSUE THREAD

**Issue by Cacanny** [start-angular/SB-Admin-BS4-Angular-2#59]
Dear devs of this template!

I have a problem with some node_modules I try to install. I also made a stackoverflow with this issue: 
http://stackoverflow.com/questions/40374805/ng2-smart-table-files-are-missing-404-not-found. I thought maybe because it's because of this template way of handling things (systemJS builder) that I have to ask it here as you are the guys that build this.

I'm not familiar with SystemJS or the Builder of it so maybe I'm just overlooking things. What I did now was adding the following lines to seed.config.ts:

SYSTEM_CONFIG_DEV : 

in paths: { 
'ng2-smart-table/ng2-smart-table': 'node_modules/ng2-smart-table/build/src/ng2-smart-table/index.js',}

in System_BUILDER_CONFIG 
packages: 
      'ng2-smart-table': {
        main: 'index.js'
      }

I still get 404 NOT FOUND 

Could you take a look and perhaps help me with this? It also doesn't always happen with other modules but also for adding the ng-bootstrap for example I had to change some config files, but I don't feel this is the proper way...

**Comment by Cacanny** [comment]
Ok, what I did now was adding one to the SYSTEM_CONFIG_DEV paths: 

'ng2-smart-table': 'node_modules/ng2-smart-table/build/src/ng2-smart-table/'

and in the packages: 

'ng2-smart-table': { main: 'index.js', defaultExtension: 'js'}


This seems to work as it doesn't display these errors anymore. What I get now is:

```
EXCEPTION: Uncaught (in promise): Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:5555/app/dashboard/ng2-smart-table/ng2-smart-table.module.js:16:25)
	    at eval (http://localhost:5555/app/dashboard/ng2-smart-table/ng2-smart-table.module.js:34:4)
	    at eval (http://localhost:5555/app/dashboard/ng2-smart-table/ng2-smart-table.module.js:35:3)
	Evaluating http://localhost:5555/node_modules/ng2-smart-table/build/src/ng2-smart-table/
	Evaluating http://localhost:5555/app/dashboard/ng2-smart-table/ng2-smart-table.module.js
	Error loading http://localhost:5555/app/dashboard/ng2-smart-table/ng2-smart-table.module.js
```

Keep in mind that the ng2-smart-table here is just a name I gave a directory in order to test the ng2-smart-table functionalities before adding it to my project.

**Comment by hernanBeiza** [comment]
Hi!
I am trying to compile to dev or prod using "npm run build.dev" but I am having problems with it. When I open index.html in /dist/dev or /dist/prod I have a lot of error 404 refered to node_modules. How I have to use this? What kind of web server I need to run this? 
Any tip I will be very appreciated. I am trying to build this for make my web app but I have problems with this step :(
