### ISSUE TITLE
Submenu item is visible while submenu is close

### ISSUE THREAD

**Issue by fnrbh** [start-angular/SB-Admin-BS4-Angular-2#68]
Hi,

When there is more sub menu items than main menu items under the submenu, then the last sub menu items are visible, as you can see from the screenshot. 

Any idea about this?

![submenu_issue](https://cloud.githubusercontent.com/assets/25104088/21933816/9c3accf4-d9af-11e6-968d-8193b2950376.png)

Thanks in Advance.
fnrbh

**Comment by juananinca** [comment]
On #48 issue there is a possible solution.
