### ISSUE TITLE
Renaming project seed

### ISSUE THREAD

**Issue by Uness77** [start-angular/SB-Admin-BS4-Angular-2#69]
Hello,

I am trying to use this template for my own project, I tried to rename the project from ''SB-Admin-BS4-Angular-2'' to ''My project'' by replacing all the matches of ''SB-Admin-BS4-Angular-2'' found in the project files. 
When I run the command : sudo npm install I get : 

npm WARN Invalid name: "My project"
npm WARN My project No description
npm WARN My project No repository field.
npm WARN My project No README data
npm WARN My project No license field.

Thanks in advance for any help you can give me
PS: I am a beginner in Angular ^^

**Comment by nitinkumarmishra** [comment]
rename your project to `My-Project` i.e `- seperated` and also change to seed.config.ts

**Comment by Uness77** [comment]
Thank you :)
