### ISSUE TITLE
Error running tests with ng2-bootstrap

### ISSUE THREAD

**Issue by chris-hammons** [start-angular/SB-Admin-BS4-Angular-2#7]
When I run npm test I get the following error messsage

> START:
> 12 04 2016 11:51:10.841:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
> 12 04 2016 11:51:10.847:INFO [launcher]: Starting browser PhantomJS2
> 12 04 2016 11:51:10.862:INFO [launcher]: Starting browser Chrome
> 12 04 2016 11:51:11.844:INFO [Chrome 49.0.2623 (Windows 7 0.0.0)]: Connected on socket /#cHqTYWOa9khwW-vxAAAA with id 66985053
> 12 04 2016 11:51:12.385:INFO [PhantomJS 2.0.0 (Windows 7 0.0.0)]: Connected on socket /#hWaQSbkcDJH5jzcLAAAB with id 51257053
> 12 04 2016 11:51:12.715:WARN [web-server]: 404: /base/ng2-bootstrap/ng2-bootstrap.js
> Chrome 49.0.2623 (Windows 7 0.0.0) ERROR: 'Error: XHR error (404 Not Found) loading http://localhost:9876/base/ng2-bootstrap/ng2-bootstrap.js
>     at error (http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?6661518ff30017d19a910845245d893379e0498c:1021:16)
>     at XMLHttpRequest.xhr.onreadystatechange [as _onreadystatechange] (http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?6661518ff30017d19a910845245d893379e0498c:1042:13)
>     at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone-microtask.js?2c40f1490bd97f0e177fa1ec2a3c3000d0f08bd4:120:17)
>     at XMLHttpRequest.zoneBoundFn (http://localhost:9876/base/node_modules/zone.js/dist/zone-microtask.js?2c40f1490bd97f0e177fa1ec2a3c3000d0f08bd4:93:19)'
> 12 04 2016 11:51:13.820:WARN [web-server]: 404: /base/ng2-bootstrap/ng2-bootstrap.js
> ERROR: Error{stack: undefined, line: 741, sourceURL: 'http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?6661518ff30017d19a910845245d893379e0498c'}
>   NameList Service
>     √ should return the list of names
> 
> Finished in 0.019 secs / 0.004 secs

**Comment by nitinkumarmishra** [comment]
currently this project not supporting testing, tools are set up but it only support production and development mode.
