### ISSUE TITLE
how to deploy on a web server (not nodejs)

### ISSUE THREAD

**Issue by jrrombaldo** [start-angular/SB-Admin-BS4-Angular-2#71]
Hello, how do you suggest to deploy this application on webserver such as tomcat?
I noticed that after a "npm build dist.dev", variables likes "<%= APP_BASE %>" are not expanded, hence it  won't work on regular webserver.

Any suggestion.
Many thanks

**Comment by nitinkumarmishra** [comment]
first you need to produce build by using command `gulp build.prod` then deploy that build to server

**Comment by jrrombaldo** [comment]
Hi Nitin,
Sorry for my ignorance, but even after run this command, my variales still not expanding. (I still having <%%> on my final html files)

Should I run something else? 

Cheers
Carlos

**Comment by jrrombaldo** [comment]
Actually, when I run the “gulp build.prod” there’s no “app” folder on distilled/prod.  On the other way, when run gulp build.dev there is an app folder under dist/dev.

So where are the HTML files being sent to?

Cheers
Carlos

**Comment by jrrombaldo** [comment]
Hello,
Could you please speficy how to build it for production. When I run "gulp build.prod", it generates no  HTML file on folder dist/prod . There is no folder app on this directory.

Thanks

**Comment by nitinkumarmishra** [comment]
run `gulp build.prod`, it will generate minified files inside `dist/prod` you need to deploy that folder only.

**Comment by jrrombaldo** [comment]
It worked.
Many thanks, its an amazing dashboard,  great work.

Cheers
