### ISSUE TITLE
Can you help with newbie question and angular cli integration?

### ISSUE THREAD

**Issue by mikeprag** [start-angular/SB-Admin-BS4-Angular-2#74]
Hi,
I am trying to integrate your SB Admin Angular 2 code with an Angular CLI generated site. I am almost there, however any components that use this syntax
`var link: any = $('<link>');`

do not work. I am getting something like,

`topnav.ts (11,19): Cannot find name '$'.)`

If I open your site in VS Code and hover over the $, it tells me it's coming from a protractor interface, cssSelectorHelper but I have no idea how to get this to work in my CLI based project. I can see in /@types there is a protractor folder with a typings file in it but I can't find any way in the CLI to get this in or reference it (if indeed that's the problem).

I am new to Angular 2 development so just trying to piece it all together. 

I'm almost there but if you could offer any help on the last bit of the puzzle, would be very grateful.

Thanks

Mike

**Comment by nitinkumarmishra** [comment]
add jquery in script array of angular-cli.json and then add `declare var $: any` at top of topnav.ts file
