### ISSUE TITLE
ng2-boostrap in layout.module.ts causes compilation error

### ISSUE THREAD

**Issue by kimfook** [start-angular/SB-Admin-BS4-Angular-2#76]
Angular CLI : v1.0.0
Node version : v7.8.0
OSX 

When I run `ng serve`, it says cannot find module `ng2-bootstrap`. If I change the two lines:
```
import { DropdownModule } from 'ng2-bootstrap';
```
to
```
import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap';
``` 
and 
```
DropdownModule.forRoot(),
``` 
to
```
NgbDropdownModule.forRoot(),
```

the error went away. 

However I am not sure if that's the correct solution.

**Comment by nitinkumarmishra** [comment]
your solution in correct `ng2-bootstrap` is not compatible with latest bootstrap, so only use `@ng-bootstra`
