### ISSUE TITLE
Toggle Sidebar Button issue on Chrome Mobile

### ISSUE THREAD

**Issue by kimfook** [start-angular/SB-Admin-BS4-Angular-2#77]
In Google Chrome mobile, the toggle sidebar button on top right corner disappeared after first click. Clicking the region again refresh the page and goes back to dashboard.

Tested on Samsung Note 7 Chrome 56.0.2924.87. Also can reproduce the problem using Desktop version with Device Mode.

**Comment by nitinkumarmishra** [comment]
Fixed
